### ISSUE TITLE
Segfault while fetching mails

### ISSUE THREAD

**Issue by kakra** [KrissN/akonadi-ews#10]
KMail was busy fetching mails when suddenly the resource crashed:

```
Application: akonadi_ews_resource (akonadi_ews_resource), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f6b16d43840 (LWP 21165))]

Thread 5 (Thread 0x7f6b1640e700 (LWP 21173)):
#0  0x0000003a1c8e0d4d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000003a1f00aac2 in poll (__timeout=-1, __nfds=1, __fds=0x7f6b1640dc60) at /usr/include/bits/poll2.h:46
#2  _xcb_conn_wait (c=c@entry=0x14798b0, cond=cond@entry=0x14798f0, vector=vector@entry=0x0, count=count@entry=0x0) at /var/tmp/portage/x11-libs/libxcb-1.11.1/work/libxcb-1.11.1/src/xcb_conn.c:459
#3  0x0000003a1f00c72f in xcb_wait_for_event (c=0x14798b0) at /var/tmp/portage/x11-libs/libxcb-1.11.1/work/libxcb-1.11.1/src/xcb_in.c:693
#4  0x00007f6b16857639 in QXcbEventReader::run (this=0x1487a60) at qxcbconnection.cpp:1325
#5  0x0000003a2c0ae928 in QThreadPrivate::start (arg=0x1487a60) at thread/qthread_unix.cpp:341
#6  0x0000003a1d007444 in start_thread (arg=0x7f6b1640e700) at pthread_create.c:334
#7  0x0000003a1c8e9dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f6b154ea700 (LWP 21181)):
#0  0x0000003a1eca46e9 in g_mutex_lock (mutex=mutex@entry=0x7f6b08000990) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gthread-posix.c:1338
#1  0x0000003a1ec539ea in g_main_context_prepare (context=context@entry=0x7f6b08000990, priority=priority@entry=0x7f6b154e9c10) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3444
#2  0x0000003a1ec544b8 in g_main_context_iterate (context=context@entry=0x7f6b08000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3820
#3  0x0000003a1ec5469c in g_main_context_iteration (context=0x7f6b08000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#4  0x0000003a2c2d7efc in QEventDispatcherGlib::processEvents (this=0x7f6b080008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:417
#5  0x0000003a2c282f2a in QEventLoop::exec (this=this@entry=0x7f6b154e9d50, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#6  0x0000003a2c0a9dc4 in QThread::exec (this=this@entry=0x3a31c8c240 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread.cpp:500
#7  0x0000003a31c157d5 in QDBusConnectionManager::run (this=0x3a31c8c240 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at qdbusconnection.cpp:189
#8  0x0000003a2c0ae928 in QThreadPrivate::start (arg=0x3a31c8c240 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread_unix.cpp:341
#9  0x0000003a1d007444 in start_thread (arg=0x7f6b154ea700) at pthread_create.c:334
#10 0x0000003a1c8e9dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f6b14ce9700 (LWP 21182)):
#0  g_mutex_unlock (mutex=0x7f6b0c000990) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gthread-posix.c:1350
#1  0x0000003a1ec5443d in g_main_context_iterate (context=context@entry=0x7f6b0c000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3788
#2  0x0000003a1ec5469c in g_main_context_iteration (context=0x7f6b0c000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#3  0x0000003a2c2d7efc in QEventDispatcherGlib::processEvents (this=0x7f6b0c0008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:417
#4  0x0000003a2c282f2a in QEventLoop::exec (this=this@entry=0x7f6b14ce8d80, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#5  0x0000003a2c0a9dc4 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:500
#6  0x0000003a2c0ae928 in QThreadPrivate::start (arg=0x14e5240) at thread/qthread_unix.cpp:341
#7  0x0000003a1d007444 in start_thread (arg=0x7f6b14ce9700) at pthread_create.c:334
#8  0x0000003a1c8e9dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f6b075ef700 (LWP 21448)):
#0  0x0000003a1c8dcd2d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000003a1eca2f90 in read (__nbytes=16, __buf=0x7f6b075eeba0, __fd=<optimized out>) at /usr/include/bits/unistd.h:44
#2  g_wakeup_acknowledge (wakeup=0x7f6b0c002390) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gwakeup.c:210
#3  0x0000003a1ec5400f in g_main_context_check (context=context@entry=0x7f6b00000990, max_priority=2147483647, fds=fds@entry=0x7f6b00003020, n_fds=n_fds@entry=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3632
#4  0x0000003a1ec54530 in g_main_context_iterate (context=context@entry=0x7f6b00000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3837
#5  0x0000003a1ec5469c in g_main_context_iteration (context=0x7f6b00000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#6  0x0000003a2c2d7efc in QEventDispatcherGlib::processEvents (this=0x7f6b000008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:417
#7  0x0000003a2c282f2a in QEventLoop::exec (this=this@entry=0x7f6b075eed80, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#8  0x0000003a2c0a9dc4 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:500
#9  0x0000003a2c0ae928 in QThreadPrivate::start (arg=0x158aa70) at thread/qthread_unix.cpp:341
#10 0x0000003a1d007444 in start_thread (arg=0x7f6b075ef700) at pthread_create.c:334
#11 0x0000003a1c8e9dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f6b16d43840 (LWP 21165)):
[KCrash Handler]
#6  0x00000000004823ae in EwsFetchItemsJob::compareItemLists (this=this@entry=0x30840f0) at /var/tmp/portage/kde-misc/akonadi-ews-0.8.0/work/akonadi-ews-0.8.0/ewsfetchitemsjob.cpp:267
#7  0x0000000000485e65 in EwsFetchItemsJob::remoteItemFetchDone (this=0x30840f0, job=<optimized out>) at /var/tmp/portage/kde-misc/akonadi-ews-0.8.0/work/akonadi-ews-0.8.0/ewsfetchitemsjob.cpp:206
#8  0x0000003a2c2afd8d in QtPrivate::QSlotObjectBase::call (a=0x7fff52725010, r=0x30840f0, this=0x15edb40) at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124
#9  QMetaObject::activate (sender=sender@entry=0x21e30b0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7fff52725010) at kernel/qobject.cpp:3715
#10 0x0000003a2c2b0347 in QMetaObject::activate (sender=sender@entry=0x21e30b0, m=m@entry=0x3a34c9a2e0 <KJob::staticMetaObject>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7fff52725010) at kernel/qobject.cpp:3595
#11 0x0000003a34a40372 in KJob::result (this=this@entry=0x21e30b0, _t1=_t1@entry=0x21e30b0) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.23.0/work/kcoreaddons-5.23.0_build/src/lib/moc_kjob.cpp:568
#12 0x0000003a34a41b41 in KJob::finishJob (this=this@entry=0x21e30b0, emitResult=emitResult@entry=true) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.23.0/work/kcoreaddons-5.23.0/src/lib/jobs/kjob.cpp:109
#13 0x0000003a34a43b2a in KJob::emitResult (this=this@entry=0x21e30b0) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.23.0/work/kcoreaddons-5.23.0/src/lib/jobs/kjob.cpp:293
#14 0x00000000004e3b57 in EwsRequest::requestResult (this=0x21e30b0, job=0x1597b80) at /var/tmp/portage/kde-misc/akonadi-ews-0.8.0/work/akonadi-ews-0.8.0/ewsclient/ewsrequest.cpp:132
#15 0x00000000004fdcc4 in EwsRequest::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at /var/tmp/portage/kde-misc/akonadi-ews-0.8.0/work/akonadi-ews-0.8.0_build/ewsclient/moc_ewsrequest.cpp:77
#16 0x0000003a2c2af625 in QMetaObject::activate (sender=sender@entry=0x1597b80, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7fff527252d0) at kernel/qobject.cpp:3730
#17 0x0000003a2c2b0347 in QMetaObject::activate (sender=sender@entry=0x1597b80, m=m@entry=0x3a34c9a2e0 <KJob::staticMetaObject>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7fff527252d0) at kernel/qobject.cpp:3595
#18 0x0000003a34a40372 in KJob::result (this=this@entry=0x1597b80, _t1=_t1@entry=0x1597b80) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.23.0/work/kcoreaddons-5.23.0_build/src/lib/moc_kjob.cpp:568
#19 0x0000003a34a41b41 in KJob::finishJob (this=this@entry=0x1597b80, emitResult=emitResult@entry=true) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.23.0/work/kcoreaddons-5.23.0/src/lib/jobs/kjob.cpp:109
#20 0x0000003a34a43b2a in KJob::emitResult (this=this@entry=0x1597b80) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.23.0/work/kcoreaddons-5.23.0/src/lib/jobs/kjob.cpp:293
#21 0x00000033a06c5a52 in KIO::SimpleJob::slotFinished (this=this@entry=0x1597b80) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0/src/core/simplejob.cpp:230
#22 0x00000033a06cf646 in KIO::TransferJob::slotFinished (this=0x1597b80) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0/src/core/transferjob.cpp:166
#23 0x00000033a06d01d1 in KIO::TransferJob::qt_static_metacall (_o=0x1597b80, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0_build/src/core/moc_transferjob.cpp:155
#24 0x0000003a2c2af625 in QMetaObject::activate (sender=sender@entry=0x1596e40, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x0) at kernel/qobject.cpp:3730
#25 0x0000003a2c2b0347 in QMetaObject::activate (sender=sender@entry=0x1596e40, m=m@entry=0x33a0978180 <KIO::SlaveInterface::staticMetaObject>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x0) at kernel/qobject.cpp:3595
#26 0x00000033a06a5c63 in KIO::SlaveInterface::finished (this=this@entry=0x1596e40) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0_build/src/core/moc_slaveinterface.cpp:424
#27 0x00000033a06a9011 in KIO::SlaveInterface::dispatch (this=0x1596e40, _cmd=<optimized out>, rawdata=...) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0/src/core/slaveinterface.cpp:160
#28 0x00000033a06a6217 in KIO::SlaveInterface::dispatch (this=0x1596e40) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0/src/core/slaveinterface.cpp:89
#29 0x00000033a06aa976 in KIO::Slave::gotInput (this=0x1596e40) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0/src/core/slave.cpp:393
#30 0x00000033a07354c5 in KIO::Slave::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0_build/src/core/moc_slave.cpp:87
#31 0x0000003a2c2af625 in QMetaObject::activate (sender=0x1587350, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3730
#32 0x0000003a2c2b0347 in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x33a0976c00 <KIO::Connection::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3595
#33 0x00000033a064e3bf in KIO::Connection::readyRead (this=<optimized out>) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0_build/src/core/moc_connection_p.cpp:142
#34 KIO::ConnectionPrivate::dequeue (this=0x157fa80) at /var/tmp/portage/kde-frameworks/kio-5.23.0/work/kio-5.23.0/src/core/connection.cpp:45
#35 0x0000003a2c2b0cca in QObject::event (this=0x1587350, e=<optimized out>) at kernel/qobject.cpp:1256
#36 0x000000339c75b86c in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x1587350, e=0x15ccc70) at kernel/qapplication.cpp:3804
#37 0x000000339c763312 in QApplication::notify (this=0x7fff52725ff0, receiver=0x1587350, e=0x15ccc70) at kernel/qapplication.cpp:3561
#38 0x0000003a2c285048 in QCoreApplication::notifyInternal2 (receiver=0x1587350, event=event@entry=0x15ccc70) at kernel/qcoreapplication.cpp:1015
#39 0x0000003a2c286e03 in QCoreApplication::sendEvent (event=0x15ccc70, receiver=<optimized out>) at kernel/qcoreapplication.h:225
#40 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x14677d0) at kernel/qcoreapplication.cpp:1650
#41 0x0000003a2c2873a8 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1508
#42 0x0000003a2c2d7b03 in postEventSourceDispatch (s=0x14bac60) at kernel/qeventdispatcher_glib.cpp:270
#43 0x0000003a1ec542ed in g_main_dispatch (context=0x7f6b100016f0) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3154
#44 g_main_context_dispatch (context=context@entry=0x7f6b100016f0) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3769
#45 0x0000003a1ec545f0 in g_main_context_iterate (context=context@entry=0x7f6b100016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3840
#46 0x0000003a1ec5469c in g_main_context_iteration (context=0x7f6b100016f0, may_block=1) at /var/tmp/portage/dev-libs/glib-2.46.2-r3/work/glib-2.46.2/glib/gmain.c:3901
#47 0x0000003a2c2d7ee7 in QEventDispatcherGlib::processEvents (this=0x14c6fa0, flags=...) at kernel/qeventdispatcher_glib.cpp:417
#48 0x0000003a2c282f2a in QEventLoop::exec (this=this@entry=0x7fff52725f50, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#49 0x0000003a2c28b29c in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1285
#50 0x000000339b8f45fc in QGuiApplication::exec () at kernel/qguiapplication.cpp:1607
#51 0x000000339c75b7c5 in QApplication::exec () at kernel/qapplication.cpp:2979
#52 0x00000033afe28c6e in Akonadi::ResourceBase::init (r=r@entry=0x14e59d0) at /var/tmp/portage/kde-apps/akonadi-16.04.2/work/akonadi-16.04.2/src/agentbase/resourcebase.cpp:605
#53 0x000000000049b7d7 in Akonadi::ResourceBase::init<EwsResource> (argc=3, argv=<optimized out>) at /usr/include/KF5/AkonadiAgentBase/resourcebase.h:196
#54 0x0000003a1c8206d0 in __libc_start_main (main=0x447840 <main(int, char**)>, argc=3, argv=0x7fff52726118, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff52726108) at libc-start.c:289
#55 0x000000000044c329 in _start ()

```

**Comment by KrissN** [comment]
This looks like a duplicate of #7

**Comment by kakra** [comment]
I think it can be closed then. Didn't happen again.

**Comment by KrissN** [comment]
Thanks for your feedback.
