### ISSUE TITLE
Intermittend crashes, maybe unstable connection

### ISSUE THREAD

**Issue by kakra** [KrissN/akonadi-ews#21]
I'm experiencing seemingly random crashes, some of them may be related to a dropped internet connection. This is one (tho I didn't see the internet connection drop this time):

````
Application: akonadi_ews_resource (akonadi_ews_resource), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f7b4fb1a840 (LWP 5895))]

Thread 6 (Thread 0x7f7b4f1d8700 (LWP 5896)):
#0  0x000000350dee0d4d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000003510e0c952 in poll (__timeout=-1, __nfds=1, __fds=0x7f7b4f1d7c60) at /usr/include/bits/poll2.h:46
#2  _xcb_conn_wait (c=c@entry=0x24fc570, cond=cond@entry=0x24fc5b0, vector=vector@entry=0x0, count=count@entry=0x0) at /var/tmp/portage/x11-libs/libxcb-1.12/work/libxcb-1.12/src/xcb_conn.c:479
#3  0x0000003510e0f169 in xcb_wait_for_event (c=0x24fc570) at /var/tmp/portage/x11-libs/libxcb-1.12/work/libxcb-1.12/src/xcb_in.c:693
#4  0x00007f7b4f621cd9 in QXcbEventReader::run (this=0x2508340) at qxcbconnection.cpp:1337
#5  0x00000038f28af7c8 in QThreadPrivate::start (arg=0x2508340) at thread/qthread_unix.cpp:344
#6  0x000000350e607444 in start_thread (arg=0x7f7b4f1d8700) at pthread_create.c:334
#7  0x000000350dee9dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7f7b4e2ac700 (LWP 5897)):
#0  g_mutex_unlock (mutex=0x7f7b40000990) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gthread-posix.c:1348
#1  0x0000003510253e3e in g_main_context_acquire (context=0x7f7b40000990) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3283
#2  0x0000003510254eb5 in g_main_context_iterate (context=context@entry=0x7f7b40000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3879
#3  0x000000351025510c in g_main_context_iteration (context=0x7f7b40000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3990
#4  0x00000038f2ad92ec in QEventDispatcherGlib::processEvents (this=0x7f7b400008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#5  0x00000038f2a8676a in QEventLoop::exec (this=this@entry=0x7f7b4e2abd50, flags=..., flags@entry=...) at kernel/qeventloop.cpp:210
#6  0x00000038f28aae84 in QThread::exec (this=this@entry=0x38f4c8d940 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread.cpp:507
#7  0x00000038f4c15aa5 in QDBusConnectionManager::run (this=0x38f4c8d940 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at qdbusconnection.cpp:196
#8  0x00000038f28af7c8 in QThreadPrivate::start (arg=0x38f4c8d940 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread_unix.cpp:344
#9  0x000000350e607444 in start_thread (arg=0x7f7b4e2ac700) at pthread_create.c:334
#10 0x000000350dee9dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f7b4daab700 (LWP 5898)):
#0  0x000000350dedcd2d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000035102a5380 in read (__nbytes=16, __buf=0x7f7b4daaaba0, __fd=<optimized out>) at /usr/include/bits/unistd.h:44
#2  g_wakeup_acknowledge (wakeup=0x7f7b400025b0) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gwakeup.c:210
#3  0x0000003510254a27 in g_main_context_check (context=context@entry=0x7f7b44000990, max_priority=2147483647, fds=fds@entry=0x7f7b44002e20, n_fds=n_fds@entry=1) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3707
#4  0x0000003510254fa0 in g_main_context_iterate (context=context@entry=0x7f7b44000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3926
#5  0x000000351025510c in g_main_context_iteration (context=0x7f7b44000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3990
#6  0x00000038f2ad92ec in QEventDispatcherGlib::processEvents (this=0x7f7b440008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#7  0x00000038f2a8676a in QEventLoop::exec (this=this@entry=0x7f7b4daaad80, flags=..., flags@entry=...) at kernel/qeventloop.cpp:210
#8  0x00000038f28aae84 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:507
#9  0x00000038f28af7c8 in QThreadPrivate::start (arg=0x2554740) at thread/qthread_unix.cpp:344
#10 0x000000350e607444 in start_thread (arg=0x7f7b4daab700) at pthread_create.c:334
#11 0x000000350dee9dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f7b4d2aa700 (LWP 5900)):
#0  0x00000035102a6ad9 in g_mutex_lock (mutex=mutex@entry=0x7f7b38000990) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gthread-posix.c:1336
#1  0x000000351025494e in g_main_context_check (context=context@entry=0x7f7b38000990, max_priority=<optimized out>, fds=fds@entry=0x7f7b38003020, n_fds=n_fds@entry=1) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3766
#2  0x0000003510254fa0 in g_main_context_iterate (context=context@entry=0x7f7b38000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3926
#3  0x000000351025510c in g_main_context_iteration (context=0x7f7b38000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3990
#4  0x00000038f2ad92ec in QEventDispatcherGlib::processEvents (this=0x7f7b380008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#5  0x00000038f2a8676a in QEventLoop::exec (this=this@entry=0x7f7b4d2a9d80, flags=..., flags@entry=...) at kernel/qeventloop.cpp:210
#6  0x00000038f28aae84 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:507
#7  0x00000038f28af7c8 in QThreadPrivate::start (arg=0x25558d0) at thread/qthread_unix.cpp:344
#8  0x000000350e607444 in start_thread (arg=0x7f7b4d2aa700) at pthread_create.c:334
#9  0x000000350dee9dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f7b3f5ef700 (LWP 5917)):
#0  0x000000350dedcd2d in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000035102a5380 in read (__nbytes=16, __buf=0x7f7b3f5eeba0, __fd=<optimized out>) at /usr/include/bits/unistd.h:44
#2  g_wakeup_acknowledge (wakeup=0x25b8e80) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gwakeup.c:210
#3  0x0000003510254a27 in g_main_context_check (context=context@entry=0x7f7b34000990, max_priority=2147483647, fds=fds@entry=0x7f7b34003020, n_fds=n_fds@entry=1) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3707
#4  0x0000003510254fa0 in g_main_context_iterate (context=context@entry=0x7f7b34000990, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3926
#5  0x000000351025510c in g_main_context_iteration (context=0x7f7b34000990, may_block=1) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3990
#6  0x00000038f2ad92ec in QEventDispatcherGlib::processEvents (this=0x7f7b340008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#7  0x00000038f2a8676a in QEventLoop::exec (this=this@entry=0x7f7b3f5eed80, flags=..., flags@entry=...) at kernel/qeventloop.cpp:210
#8  0x00000038f28aae84 in QThread::exec (this=<optimized out>) at thread/qthread.cpp:507
#9  0x00000038f28af7c8 in QThreadPrivate::start (arg=0x2670610) at thread/qthread_unix.cpp:344
#10 0x000000350e607444 in start_thread (arg=0x7f7b3f5ef700) at pthread_create.c:334
#11 0x000000350dee9dad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f7b4fb1a840 (LWP 5895)):
[KCrash Handler]
#6  0x00000000004aece9 in QString::QString (other=..., this=0x7ffc5aed9450) at /usr/include/qt5/QtCore/qstring.h:898
#7  EwsRequest::Response::responseCode (this=0x0) at /var/tmp/portage/kde-misc/akonadi-ews-0.8.1/work/akonadi-ews-0.8.1/ewsclient/ewsrequest.h:46
#8  EwsSubscriptionManager::getEventsRequestFinished (this=0x2658380, job=0x3d59440) at /var/tmp/portage/kde-misc/akonadi-ews-0.8.1/work/akonadi-ews-0.8.1/ewssubscriptionmanager.cpp:205
#9  0x00000038f2ab19ee in QtPrivate::QSlotObjectBase::call (a=0x7ffc5aed9630, r=0x2658380, this=0x31fa860) at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:130
#10 QMetaObject::activate (sender=sender@entry=0x3d59440, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7ffc5aed9630) at kernel/qobject.cpp:3723
#11 0x00000038f2ab1f87 in QMetaObject::activate (sender=sender@entry=0x3d59440, m=m@entry=0x38f589a2e0 <KJob::staticMetaObject>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7ffc5aed9630) at kernel/qobject.cpp:3602
#12 0x00000038f5640272 in KJob::result (this=this@entry=0x3d59440, _t1=_t1@entry=0x3d59440) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.28.0/work/kcoreaddons-5.28.0_build/src/lib/moc_kjob.cpp:568
#13 0x00000038f5641a41 in KJob::finishJob (this=this@entry=0x3d59440, emitResult=emitResult@entry=true) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.28.0/work/kcoreaddons-5.28.0/src/lib/jobs/kjob.cpp:109
#14 0x00000038f5643a2a in KJob::emitResult (this=this@entry=0x3d59440) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.28.0/work/kcoreaddons-5.28.0/src/lib/jobs/kjob.cpp:293
#15 0x00000000004f5b37 in EwsRequest::requestResult (this=0x3d59440, job=0x3d7f7b0) at /var/tmp/portage/kde-misc/akonadi-ews-0.8.1/work/akonadi-ews-0.8.1/ewsclient/ewsrequest.cpp:140
#16 0x00000000005102d4 in EwsRequest::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at /var/tmp/portage/kde-misc/akonadi-ews-0.8.1/work/akonadi-ews-0.8.1_build/ewsclient/moc_ewsrequest.cpp:77
#17 0x00000038f2ab1262 in QMetaObject::activate (sender=sender@entry=0x3d7f7b0, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7ffc5aed98f0) at kernel/qobject.cpp:3740
#18 0x00000038f2ab1f87 in QMetaObject::activate (sender=sender@entry=0x3d7f7b0, m=m@entry=0x38f589a2e0 <KJob::staticMetaObject>, local_signal_index=local_signal_index@entry=3, argv=argv@entry=0x7ffc5aed98f0) at kernel/qobject.cpp:3602
#19 0x00000038f5640272 in KJob::result (this=this@entry=0x3d7f7b0, _t1=_t1@entry=0x3d7f7b0) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.28.0/work/kcoreaddons-5.28.0_build/src/lib/moc_kjob.cpp:568
#20 0x00000038f5641a41 in KJob::finishJob (this=this@entry=0x3d7f7b0, emitResult=emitResult@entry=true) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.28.0/work/kcoreaddons-5.28.0/src/lib/jobs/kjob.cpp:109
#21 0x00000038f5643a2a in KJob::emitResult (this=this@entry=0x3d7f7b0) at /var/tmp/portage/kde-frameworks/kcoreaddons-5.28.0/work/kcoreaddons-5.28.0/src/lib/jobs/kjob.cpp:293
#22 0x00000030e68c7742 in KIO::SimpleJob::slotFinished (this=this@entry=0x3d7f7b0) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0/src/core/simplejob.cpp:230
#23 0x00000030e68d1336 in KIO::TransferJob::slotFinished (this=0x3d7f7b0) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0/src/core/transferjob.cpp:166
#24 0x00000030e68c5fcb in KIO::SimpleJob::slotError (this=0x3d7f7b0, err=<optimized out>, errorText=...) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0/src/core/simplejob.cpp:243
#25 0x00000030e68c61df in KIO::SimpleJob::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0_build/src/core/moc_simplejob.cpp:102
#26 0x00000038f2ab1262 in QMetaObject::activate (sender=sender@entry=0x36bf790, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=2, argv=argv@entry=0x7ffc5aed9cc0) at kernel/qobject.cpp:3740
#27 0x00000038f2ab1f87 in QMetaObject::activate (sender=sender@entry=0x36bf790, m=m@entry=0x30e6b7b180 <KIO::SlaveInterface::staticMetaObject>, local_signal_index=local_signal_index@entry=2, argv=argv@entry=0x7ffc5aed9cc0) at kernel/qobject.cpp:3602
#28 0x00000030e68a7796 in KIO::SlaveInterface::error (this=this@entry=0x36bf790, _t1=149, _t2=...) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0_build/src/core/moc_slaveinterface.cpp:412
#29 0x00000030e68aabf7 in KIO::SlaveInterface::dispatch (this=0x36bf790, _cmd=<optimized out>, rawdata=...) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0/src/core/slaveinterface.cpp:192
#30 0x00000030e68a7d97 in KIO::SlaveInterface::dispatch (this=0x36bf790) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0/src/core/slaveinterface.cpp:89
#31 0x00000030e68ac4f6 in KIO::Slave::gotInput (this=0x36bf790) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0/src/core/slave.cpp:398
#32 0x00000030e6937785 in KIO::Slave::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0_build/src/core/moc_slave.cpp:87
#33 0x00000038f2ab1262 in QMetaObject::activate (sender=0x3e0cd40, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3740
#34 0x00000038f2ab1f87 in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x30e6b79c00 <KIO::Connection::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x0) at kernel/qobject.cpp:3602
#35 0x00000030e684e54f in KIO::Connection::readyRead (this=<optimized out>) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0_build/src/core/moc_connection_p.cpp:142
#36 KIO::ConnectionPrivate::dequeue (this=0x40805c0) at /var/tmp/portage/kde-frameworks/kio-5.28.0/work/kio-5.28.0/src/core/connection.cpp:45
#37 0x00000038f2ab2a6a in QObject::event (this=0x3e0cd40, e=<optimized out>) at kernel/qobject.cpp:1263
#38 0x00000030e115b9fc in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x3e0cd40, e=0x47550c0) at kernel/qapplication.cpp:3799
#39 0x00000030e1163242 in QApplication::notify (this=0x7ffc5aeda670, receiver=0x3e0cd40, e=0x47550c0) at kernel/qapplication.cpp:3556
#40 0x00000038f2a885e8 in QCoreApplication::notifyInternal2 (receiver=0x3e0cd40, event=event@entry=0x47550c0) at kernel/qcoreapplication.cpp:988
#41 0x00000038f2a8a613 in QCoreApplication::sendEvent (event=0x47550c0, receiver=<optimized out>) at kernel/qcoreapplication.h:231
#42 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x24c7da0) at kernel/qcoreapplication.cpp:1649
#43 0x00000038f2a8ab78 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1503
#44 0x00000038f2ad8ef3 in postEventSourceDispatch (s=0x252f040) at kernel/qeventdispatcher_glib.cpp:276
#45 0x0000003510254d5d in g_main_dispatch (context=0x7f7b480016f0) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3203
#46 g_main_context_dispatch (context=context@entry=0x7f7b480016f0) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3856
#47 0x0000003510255060 in g_main_context_iterate (context=context@entry=0x7f7b480016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3929
#48 0x000000351025510c in g_main_context_iteration (context=0x7f7b480016f0, may_block=1) at /var/tmp/portage/dev-libs/glib-2.50.1/work/glib-2.50.1/glib/gmain.c:3990
#49 0x00000038f2ad92d7 in QEventDispatcherGlib::processEvents (this=0x253fc40, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#50 0x00000038f2a8676a in QEventLoop::exec (this=this@entry=0x7ffc5aeda5d0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:210
#51 0x00000038f2a8ea2c in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1261
#52 0x00000030e06f489c in QGuiApplication::exec () at kernel/qguiapplication.cpp:1639
#53 0x00000030e115b955 in QApplication::exec () at kernel/qapplication.cpp:2975
#54 0x00000030f2828d5e in Akonadi::ResourceBase::init (r=r@entry=0x254da50) at /var/tmp/portage/kde-apps/akonadi-16.08.2/work/akonadi-16.08.2/src/agentbase/resourcebase.cpp:605
#55 0x00000000004aab17 in Akonadi::ResourceBase::init<EwsResource> (argc=3, argv=<optimized out>) at /usr/include/KF5/AkonadiAgentBase/resourcebase.h:196
#56 0x000000350de206d0 in __libc_start_main (main=0x44ab60 <main(int, char**)>, argc=3, argv=0x7ffc5aeda798, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc5aeda788) at libc-start.c:289
#57 0x000000000044f6e9 in _start ()
````

**Comment by KrissN** [comment]
This is unfortunately a known issue that I have found after releasing 0.8.1. This has already been fixed in master in commit 17b5d28.

If you are able to build a version from master then I'd appreciate if you let me know if this is actually fixed.

**Comment by kakra** [comment]
I've rebuilt 0.8.1 with this patch applied and let you know...

**Comment by hlavki** [comment]
I've addded this patch to openSUSE [package](https://build.opensuse.org/package/show/home:hlavki/akonadi-ews) and it works without any crash.

**Comment by kakra** [comment]
I think this can be closed then, a also no longer experience crashes.
